import './globals.scss';
// import {
//   Alternates,
//   Courier_Prime,
//   Inter,
//   Montserrat,
// } from '@next/font/google';
// import { Inter } from 'next/font/google';
import styles from './layout.module.scss';

// const CourierPrime = Courier_Prime({
//   weight: '400',
//   subsets: ['latin'],
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.html}>
      <body className={styles.body}> {children}</body>
    </html>
  );
}
